version: "2"

services:

  extract:
    container_name: sampleogghandler_extract_1
    image: oracle/db-12.2-goldengate-standard:18.1.0.0.0-patched
    environment:
      ORACLE_PWD: "w"
      ORACLE_SID: "ORCLCDB"
    volumes:
      - ./v_dirprm:/u01/app/ogg/dirprm
      - ./v_common:/common
      - ./v_ext:/prv

  replicat:
    container_name: sampleogghandler_replicat_1
    image: oracle/goldengate-standard-bigdata:12.3.0.1.2
    volumes:
      - ./v_dirprm:/u01/app/ogg/dirprm
      - ./v_common:/common
      - ./v_rep:/prv

  pilosa:
    container_name: sampleogghandler_pilosa_1
    image: pilosa/pilosa:master
