version: "2"

services:

  extract:
    image: oracle/goldengate-standard:18.1.0.0.0-patched
    environment:
      ORACLE_PWD: "w"
      ORACLE_SID: "ORCLCDB"
    volumes:
      - ./v_dirprm:/u01/app/ogg/dirprm
      - ./v_common:/common
      - ./v_ext:/prv

  replicat:
    image: pilosa/gg-jadapter:12.3
    volumes:
      - ./v_dirprm:/u01/app/ogg/dirprm
      - ./v_common:/common
      - ./v_rep:/prv

  pilosa:
      image: pilosa/pilosa:master
