FROM oracle/goldengate-standard:18.1.0.0.0

COPY etc/pam.d/runuser /etc/pam.d/runuser
COPY etc/pam.d/su /etc/pam.d/su
COPY opt/oracle/oradata/dbconfig/ORCLCDB/tnsnames.ora /opt/oracle/oradata/dbconfig/ORCLCDB/tnsnames.ora
